### ISSUE TITLE
Documentação doxygen não está funcionando no github pages.

### ISSUE THREAD

**Issue by Anders1232** [Anders1232/SimpleCVariableSizeVector#2]
Esta'dando o erro 404, mesmo com o repositório configurado para ter uma github page na pasta docs e nessa pasta estando o index.html gerado.

Esse é o link que deveria estar funcionando:
https://anders1232.github.io/SimpleCVariableSizeVector/

**Comment by pedrotst** [comment]
Aqui tá funfando ok 

![adsf](https://cloud.githubusercontent.com/assets/6591091/22070232/0ac5212e-dd7a-11e6-963f-ae5c6c7d979a.png)

**Comment by Anders1232** [comment]
Valeu pelo feedback! Acho então que basta esperar algum tempo pro site se tornar online.
